r"""
Write a complete OpenFOAM case for the tri-tiltrotor, from params.py.

Targets ESI OpenFOAM (v2312 and later): `simpleFoam`, and turbulence declared
in constant/turbulenceProperties. The Foundation build (openfoam12) renames
that file to momentumTransport and will reject this case -- pick one, and this
picks ESI because it is the one more commonly seen in industry.

WHAT THIS CASE MEASURES. Steady incompressible RANS around the unpowered
airframe, swept over angle of attack, to produce CL and CD -- and therefore a
measured drag polar to set against the one params.py derives from thin-airfoil
theory. That polar is currently the least-tested claim in the project.

READ THIS BEFORE TRUSTING A NUMBER. The chord Reynolds number here is
~330,000 at cruise and ~223,000 at loiter. That is low-Re transitional flow:
the real boundary layer runs laminar over a good fraction of the chord and can
separate into a bubble before it reattaches turbulent. A fully-turbulent
k-omega SST run assumes turbulent flow from the leading edge and will
OVERPREDICT skin-friction drag, typically by a large margin at this scale. The
case therefore defaults to the k-kL-omega transition model. Nothing here makes
RANS trustworthy at Re 2e5 -- treat the output as an engineering estimate to be
bracketed against XFOIL/AVL, not as truth.

Run:
    .\.venv-cad\Scripts\python.exe projects\04-tiltrotor-vtol\cad\gen_cfd_case.py
    .\.venv-cad\Scripts\python.exe ...\gen_cfd_case.py --alpha 4 --model kOmegaSST
"""

from __future__ import annotations

import argparse
import math
import shutil
from pathlib import Path

import params as P

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
CFD = PROJECT / "cfd"

HEAD = """/*--------------------------------*- C++ -*----------------------------------*\\
| GENERATED by cad/gen_cfd_case.py -- DO NOT EDIT, regenerate instead        |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    {extra}object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def head(cls, obj, location=None):
    extra = f'location    "{location}";\n    ' if location else ""
    return HEAD.format(cls=cls, obj=obj, extra=extra)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # LF only. A CRLF OpenFOAM dictionary parses, but a CRLF *script* does not
    # run under bash, and mixing the two in one tree is how that gets missed.
    path.write_bytes(text.encode("utf-8").replace(b"\r\n", b"\n"))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--alpha", type=float, default=0.0,
                    help="angle of attack, degrees")
    ap.add_argument("--speed", type=float, default=None,
                    help="freestream speed, m/s (default: cruise from params)")
    ap.add_argument("--model", default="kkLOmega",
                    choices=["kkLOmega", "kOmegaSST"],
                    help="kkLOmega is transition-sensitive and is the right "
                         "default at this Reynolds number; kOmegaSST is fully "
                         "turbulent and will overpredict drag")
    ap.add_argument("--iterations", type=int, default=3000)
    ap.add_argument("--procs", type=int, default=16)
    ap.add_argument("--max-cells", type=int, default=5_000_000,
                    help="snappyHexMesh maxGlobalCells. Meshing needs roughly "
                         "1 GB per million cells plus overhead, so this must "
                         "fit the RAM WSL actually has (`free -g`), not the "
                         "RAM the machine has.")
    args = ap.parse_args()

    P.check()
    d = P.solve()

    V = args.speed if args.speed is not None else P.V_CRUISE
    a = math.radians(args.alpha)
    nu = 1.5e-5

    # Body axes: +x forward (nose at +0.538), +z up. The aircraft flies toward
    # +x, so the freestream blows toward -x. At positive alpha the relative
    # wind arrives from below, which is a +z component.
    U = (-V * math.cos(a), 0.0, V * math.sin(a))
    drag_dir = (-math.cos(a), 0.0, math.sin(a))     # along the freestream
    lift_dir = (math.sin(a), 0.0, math.cos(a))      # perpendicular, up

    # Inlet turbulence. 0.1% intensity and a length scale of one MAC is
    # representative of still air; the transition model is sensitive to these,
    # which is itself a reason to treat the result as an estimate.
    Ti = 0.001
    k = 1.5 * (V * Ti) ** 2
    omega = k ** 0.5 / (0.09 ** 0.25 * 0.1 * d.mac)

    b = P.WING_SPAN
    # Farfield: 5 spans up/out, 10 spans downstream (-x). Small enough to mesh
    # on 16 threads, large enough that the walls do not load the wing.
    x_hi, x_lo = +5 * b, -10 * b
    y_hi = z_hi = 5 * b
    y_lo = z_lo = -5 * b
    base = 0.40                                      # background cell, m
    nx = int(round((x_hi - x_lo) / base))
    ny = int(round((y_hi - y_lo) / base))
    nz = int(round((z_hi - z_lo) / base))

    # A cell centre, well ahead of and above the nose and clear of every solid.
    def _cell_centre(lo, n_from_lo):
        return lo + base * (n_from_lo + 0.5)
    loc = (_cell_centre(x_lo, 58), _cell_centre(y_lo, 30), _cell_centre(z_lo, 30))

    case = CFD / "case"
    for sub in ("0", "system", "constant/triSurface"):
        (case / sub).mkdir(parents=True, exist_ok=True)

    stl = CFD / "geometry" / "tri_tiltrotor.stl"
    if not stl.exists():
        raise SystemExit(f"{stl} missing -- run cad/gen_cfd_surface.py first")
    shutil.copyfile(stl, case / "constant" / "triSurface" / "tri_tiltrotor.stl")

    regions = ["fuselage", "wing", "tail", "aileron_left", "aileron_right",
               "ruddervator_left", "ruddervator_right",
               "nacelle_yoke_left", "nacelle_yoke_right",
               "nacelle_cradle_left", "nacelle_cradle_right",
               "tail_motor_mount"]

    # ---------------------------------------------------------------- system
    write(case / "system" / "controlDict", head("dictionary", "controlDict") + f"""
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {args.iterations};
deltaT          1;
writeControl    timeStep;
writeInterval   500;
purgeWrite      2;
writeFormat     binary;
writePrecision  8;
runTimeModifiable true;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   1;
        log             no;
        patches         ({' '.join('aircraft_' + r for r in regions)});
        rho             rhoInf;
        rhoInf          {P.RHO};
        magUInf         {V};
        lRef            {d.mac};
        Aref            {d.wing_area};
        CofR            (0 0 0);
        liftDir         ({lift_dir[0]:.8f} {lift_dir[1]:.1f} {lift_dir[2]:.8f});
        dragDir         ({drag_dir[0]:.8f} {drag_dir[1]:.1f} {drag_dir[2]:.8f});
        pitchAxis       (0 1 0);
    }}

    // Stop as soon as the residuals are down rather than always burning the
    // full iteration count -- an alpha sweep is many runs, not one.
    residuals
    {{
        type            solverInfo;
        libs            (utilityFunctionObjects);
        fields          (U p k);
        writeControl    timeStep;
    }}
}}
""")

    write(case / "system" / "fvSchemes", head("dictionary", "fvSchemes") + """
ddtSchemes      { default steadyState; }
gradSchemes     { default cellLimited Gauss linear 1; }

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss limitedLinear 1;
    div(phi,omega)  bounded Gauss limitedLinear 1;
    div(phi,kt)     bounded Gauss limitedLinear 1;
    div(phi,kl)     bounded Gauss limitedLinear 1;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes    { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes       { default corrected; }
wallDist            { method meshWave; }
""")

    write(case / "system" / "fvSolution", head("dictionary", "fvSolution") + """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|k|omega|kt|kl)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.05;
    }
}

SIMPLE
{
    consistent          yes;
    nNonOrthogonalCorrectors 1;
    residualControl
    {
        p               1e-5;
        U               1e-6;
        "(k|omega|kt|kl)" 1e-6;
    }
}

relaxationFactors
{
    equations
    {
        U               0.9;
        ".*"            0.7;
    }
}
""")

    write(case / "system" / "blockMeshDict", head("dictionary", "blockMeshDict") + f"""
scale   1;

vertices
(
    ({x_lo} {y_lo} {z_lo}) ({x_hi} {y_lo} {z_lo})
    ({x_hi} {y_hi} {z_lo}) ({x_lo} {y_hi} {z_lo})
    ({x_lo} {y_lo} {z_hi}) ({x_hi} {y_lo} {z_hi})
    ({x_hi} {y_hi} {z_hi}) ({x_lo} {y_hi} {z_hi})
);

blocks ( hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1) );

boundary
(
    // Flow runs from +x to -x, so the INLET is the +x face.
    inlet  {{ type patch;  faces ((1 2 6 5)); }}
    outlet {{ type patch;  faces ((0 4 7 3)); }}
    farfield
    {{
        type patch;
        faces ((0 1 5 4) (3 7 6 2) (0 3 2 1) (4 5 6 7));
    }}
);
""")

    # Two DIFFERENT region blocks, which is the trap. Under `geometry` a
    # region only renames the STL solid to a patch name and OpenFOAM demands
    # `name` there; under `refinementSurfaces` it carries the refinement
    # levels. Using the refinement form in both places fails with
    #     Entry 'name' not found in dictionary ".../regions/fuselage"
    # which does not obviously say "wrong block".
    geom_regions = chr(10).join(
        f"                {r} {{ name aircraft_{r}; }}" for r in regions)
    surf_regions = "\n".join(
        f"                {r} {{ level (5 6); patchInfo {{ type wall; }} }}"
        for r in regions)

    write(case / "system" / "snappyHexMeshDict",
          head("dictionary", "snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       true;

geometry
{{
    tri_tiltrotor.stl
    {{
        type triSurfaceMesh;
        name aircraft;
        regions
        {{
{geom_regions}
        }}
    }}
    nearBox   {{ type searchableBox; min (-1.4 -1.3 -0.5); max (1.0 1.3 0.6); }}
    wakeBox   {{ type searchableBox; min (-6.0 -1.6 -0.9); max (1.2 1.6 1.0); }}
}}

castellatedMeshControls
{{
    maxLocalCells       2000000;
    maxGlobalCells      {args.max_cells};
    minRefinementCells  10;
    nCellsBetweenLevels 3;
    resolveFeatureAngle 30;
    allowFreeStandingZoneFaces true;
    maxLoadUnbalance    0.10;

    features ( {{ file "tri_tiltrotor.eMesh"; level 6; }} );

    refinementSurfaces
    {{
        aircraft
        {{
            level (5 6);
            patchInfo {{ type wall; }}
            regions
            {{
{surf_regions}
            }}
        }}
    }}

    refinementRegions
    {{
        wakeBox {{ mode inside; levels ((1e15 2)); }}
        nearBox {{ mode inside; levels ((1e15 4)); }}
    }}

    // Must be OUTSIDE every solid AND strictly inside a cell -- not on a face.
    // (3 2 2) looked fine and failed: with a 0.4 m background cell starting at
    // y = z = -10, the values 2.0 land exactly on a cell boundary and snappy
    // reports "Point (3 2 2) is not inside the mesh" while quoting a bounding
    // box that plainly contains it. This point is computed to sit at a cell
    // CENTRE, so it cannot regress if the domain or base size changes.
    locationInMesh ({loc[0]:.4f} {loc[1]:.4f} {loc[2]:.4f});
}}

snapControls
{{
    nSmoothPatch    3;
    tolerance       2.0;
    nSolveIter      50;
    nRelaxIter      6;
    nFeatureSnapIter 12;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes       true;
    expansionRatio      1.2;
    finalLayerThickness 0.5;
    minThickness        0.05;
    nGrow               0;
    layers {{ "aircraft_.*" {{ nSurfaceLayers 8; }} }}
    featureAngle        160;
    slipFeatureAngle    30;
    nRelaxIter          5;
    nSmoothSurfaceNormals 1;
    nSmoothNormals      3;
    nSmoothThickness    10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle  90;
    nBufferCellsNoExtrude 0;
    nLayerIter          50;
    nRelaxedIter        20;
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-15;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.02;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
}}

mergeTolerance 1e-6;
""")

    # surfaceFeatureExtract, NOT surfaceFeatures. ESI OpenFOAM 2412 ships only
    # the former; the latter exists in some Foundation builds and in older ESI
    # releases, reads a differently-named dict, and its absence shows up as
    # "cannot find file surfaceFeatureExtractDict" from the fallback -- an
    # error that names the wrong problem.
    write(case / "system" / "surfaceFeatureExtractDict",
          head("dictionary", "surfaceFeatureExtractDict") + """
tri_tiltrotor.stl
{
    extractionMethod    extractFromSurface;
    extractFromSurfaceCoeffs { includedAngle 150; }
    subsetFeatures      { nonManifoldEdges no; openEdges yes; }
    writeObj            no;
}
""")

    write(case / "system" / "decomposeParDict",
          head("dictionary", "decomposeParDict") + f"""
numberOfSubdomains {args.procs};
method          hierarchical;
coeffs          {{ n ({args.procs // 4} 2 2); }}
""")

    write(case / "system" / "meshQualityDict",
          head("dictionary", "meshQualityDict")
          + '#includeEtc "caseDicts/meshQualityDict"\n')

    # -------------------------------------------------------------- constant
    write(case / "constant" / "transportProperties",
          head("dictionary", "transportProperties") + f"""
transportModel  Newtonian;
nu              {nu};
""")

    write(case / "constant" / "turbulenceProperties",
          head("dictionary", "turbulenceProperties") + f"""
simulationType  RAS;
RAS
{{
    model           {args.model};
    turbulence      on;
    printCoeffs     on;
}}
""")

    # --------------------------------------------------------------------- 0
    patches = " ".join(f'"aircraft_{r}"' for r in regions)

    def field(obj, cls, dims, internal, inlet_bc, wall_bc, extra=""):
        return head(cls, obj, "0") + f"""
dimensions      {dims};
internalField   uniform {internal};

boundaryField
{{
    inlet    {{ {inlet_bc} }}
    outlet   {{ type inletOutlet; inletValue $internalField; value $internalField; }}
    farfield {{ type slip; }}
    "aircraft_.*" {{ {wall_bc} }}
}}
{extra}"""

    write(case / "0" / "U", head("volVectorField", "U", "0") + f"""
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform ({U[0]:.6f} {U[1]:.1f} {U[2]:.6f});

boundaryField
{{
    inlet    {{ type fixedValue; value $internalField; }}
    outlet   {{ type inletOutlet; inletValue uniform (0 0 0); value $internalField; }}
    farfield {{ type slip; }}
    "aircraft_.*" {{ type noSlip; }}
}}
""")

    write(case / "0" / "p", head("volScalarField", "p", "0") + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    inlet    { type zeroGradient; }
    outlet   { type fixedValue; value uniform 0; }
    farfield { type slip; }
    "aircraft_.*" { type zeroGradient; }
}
""")

    write(case / "0" / "nut", head("volScalarField", "nut", "0") + """
dimensions      [0 2 -1 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    inlet    { type calculated; value uniform 0; }
    outlet   { type calculated; value uniform 0; }
    farfield { type calculated; value uniform 0; }
    // Layers are resolved to the wall, so this is a low-Re wall treatment,
    // NOT a wall function. Check y+ after the first run.
    "aircraft_.*" { type nutLowReWallFunction; value uniform 0; }
}
""")

    if args.model == "kOmegaSST":
        write(case / "0" / "k", field(
            "k", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k:.6e}",
            "type fixedValue; value $internalField;",
            "type kLowReWallFunction; value $internalField;"))
    else:
        # kkLOmega solves turbulent (kt) and laminar (kl) kinetic energy.
        write(case / "0" / "kt", field(
            "kt", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k:.6e}",
            "type fixedValue; value $internalField;",
            "type fixedValue; value uniform 0;"))
        write(case / "0" / "kl", field(
            "kl", "volScalarField", "[0 2 -2 0 0 0 0]", "0",
            "type fixedValue; value uniform 0;",
            "type fixedValue; value uniform 0;"))

    write(case / "0" / "omega", field(
        "omega", "volScalarField", "[0 0 -1 0 0 0 0]", f"{omega:.6e}",
        "type fixedValue; value $internalField;",
        "type omegaWallFunction; value $internalField;"))

    # Empty marker file so ParaView's OpenFOAM reader can open the case
    # directly. The case lives on the Windows filesystem, so Windows-native
    # ParaView reads it with no WSL and no X11 -- which sidesteps the WSLg
    # black-window problem entirely rather than working around it.
    (case / "case.foam").write_bytes(b"")

    print(f"wrote OpenFOAM case -> {case}")
    print(f"  model        {args.model}")
    print(f"  alpha        {args.alpha:+.2f} deg")
    print(f"  U_inf        ({U[0]:.4f}, {U[1]:.1f}, {U[2]:.4f})  |U| = {V:.2f} m/s")
    print(f"  liftDir      ({lift_dir[0]:.5f} 0 {lift_dir[2]:.5f})")
    print(f"  dragDir      ({drag_dir[0]:.5f} 0 {drag_dir[2]:.5f})")
    print(f"  Aref         {d.wing_area} m^2   lRef {d.mac} m")
    print(f"  Re(MAC)      {V * d.mac / nu:,.0f}")
    print(f"  background   {nx} x {ny} x {nz} = {nx*ny*nz:,} cells "
          f"at {base} m, domain x[{x_lo},{x_hi}] y[{y_lo},{y_hi}] z[{z_lo},{z_hi}]")
    print(f"  decomposed   {args.procs} subdomains")
    print()
    print("next:  bash cfd/run_case.sh")


if __name__ == "__main__":
    main()
